# Generated by Django 4.2.5 on 2023-10-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_content_alter_post_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topics',
            field=models.ManyToManyField(blank=True, null=True, related_name='blog_posts', to='blog.topic'),
        ),
    ]
