# Generated by Django 4.2.5 on 2023-11-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_post_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoContestSubmissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('submitted', models.DateTimeField(blank=True, help_text='The date & time this photo was submitted', null=True)),
            ],
            options={
                'ordering': ['-submitted'],
            },
        ),
    ]
