# Generated by Django 4.2.5 on 2023-11-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_photocontestsubmissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photocontestsubmissions',
            name='submitted',
            field=models.DateTimeField(auto_now=True, help_text='The date & time this photo was submitted', null=True),
        ),
    ]
