# Generated by Django 4.2.5 on 2023-11-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_photocontestsubmissions_submitted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photocontestsubmissions',
            options={'ordering': ['-submitted', 'last_name', 'first_name', 'email']},
        ),
        migrations.AlterField(
            model_name='photocontestsubmissions',
            name='submitted',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
