# Generated by Django 4.2.5 on 2023-11-22 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_photocontestsubmissions_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photocontestsubmissions',
            options={'ordering': ['-submitted']},
        ),
    ]
